lang: en
timezone: America/Los_Angeles

title: bscit.dev

description: >-
  Personal website related to any and all things bscit

url: "https://bscit.dev"

github:
  username: tmaster-terrarian

twitter:
  username: bscit_dev

social:
  name: bscit
  email: bscitdv@gmail.com
  links:
    - https://github.com/tmaster-terrarian
    - https://bsky.app/profile/bscit.dev

encoding: utf-8

markdown: CommonMark
commonmark:
  options: ['UNSAFE', 'HARDBREAKS', 'STRIKETHROUGH_DOUBLE_TILDE', 'FOOTNOTES']
  extensions:
    header_ids: true
    multiline_block_quotes: true
    underline: true

defaults:
  - scope:
      path: ""
    values:
      author: bscit
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /log/:year-:month-:day:output_ext

collections:
  wiki:
    output: true
    permalink: /site/:title:output_ext
    wiki: true
  site:
    output: true
    permalink: /site/:title:output_ext
  articles:
    output: true
    permalink: /site/:title:output_ext

baseurl: ""

strict_front_matter: true

plugins:
  - jekyll-wikirefs
  - jekyll-titles-from-headings

wikilinks:
  attributes:
    enabled: true
  css:
    exclude: []
    name:
      typed: 'typed'
      wiki: 'wiki-link'
      web: 'web-link'
      invalid_wiki: 'invalid-wiki-link'
      # embed_container: 'embed-container'
      # embed_title: 'embed-title'
      # embed_content: 'embed-content'
      # embed_link: 'embed-wiki-link'
      # embed_image_container: 'embed-image-container'
      # embed_image: 'embed-image'
  enabled: true
  exclude: []

# file handling
source: ./src
destination: ./site

exclude:
- .git/
- .github/
- .vscode/
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- serve.sh
- serve.bat

keep_files:
- webdav.json
- music/
- ignorethis/
