# metadata
lang: en
timezone: America/Los_Angeles

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: bscit.dev

description: >- # used by seo meta and the atom feed
  Personal website related to any and all things bscit

url: "https://bscit.dev"

github:
  username: tmaster-terrarian

twitter:
  username: bscit_dev
  card: summary_large_image

social:
  # Will be displayed as the default author of the posts and the copyright owner in the Footer
  name: bscit
  # email: example@domain.com # change to your email address
  links:
    - https://github.com/tmaster-terrarian
    - https://twitter.com/bscit_dev

# ↑ --------------------------

# jekyll-spaceship settings › https://github.com/jeffreytse/jekyll-spaceship/blob/master/README.md
# ↓ --------------------------
# Where things are
jekyll-spaceship:
  # default enabled processors
  processors:
    - mathjax-processor
    - polyfill-processor
    - emoji-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
        displayMath:
          - ['$$','$$']
          - ['\[','\]']
      svg:
        fontCache: 'global'
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: []   # include patterns for math expressions checking (regexp)
      exclude: []   # exclude patterns for math expressions checking (regexp)
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/

# ↑ --------------------------

defaults:
  - scope:
      path: ""
    values:
      image: /images/thumb.png
      author: bscit
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /posts/:categories/:title:output_ext

baseurl: ""

strict_front_matter: true

plugins:
  - jekyll-seo-tag
  - jekyll-spaceship

# file handling
source: ./src
destination: ./public

exclude:
- .git/
- .github/
- .vscode/
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- serve.sh

keep_files:
- webdav.json
- music/
- ignorethis/
