meta:
  title: bscit.dev
  title_template: %s - bscit.dev
  author: bscit
  site_name: bscit
  robots: noarchive

site:
  origin: https://bscit.dev
  skip: [.vscode, "*.sh"]

rss:
  enabled: true
  title: bscit book
  description: bscit's published writing
  collection: writing

design:
  inline_css: true

collections:
  writing:
    include: [site/writing/]
    require: [title, date]
    skip: [draft]
    sort: date desc
  log_2026:
    include: [site/log/2026/]
    require: [title]
    skip: [draft]
    sort: date title
  recipes_meals:
    include: [site/recipes/meals/]
    require: [title]
    skip: [hide]
    sort: title
  recipes_sides:
    include: [site/recipes/sides/]
    require: [title]
    skip: [hide]
    sort: title
  recipes_desserts:
    include: [site/recipes/desserts/]
    require: [title]
    skip: [hide]
    sort: title
  recipes_all:
    include: [site/recipes/]
    require: [title]
    skip: [hide]
    sort: title

content:
  heading_ids: true
